### ISSUE TITLE
AR Required but Statz Throwing exceptions

### ISSUE THREAD

**Issue by myxxmikeyxx** [Staartvin/Statz#106]
Statz is throwing this error anytime anyone does pretty mush anything, I noticed it when i had the server up and I was in a chest clicking on items and moving them around. Can you disable AutoRank's dependency on Statz? I just know then when I don't have Statz installed AR doesn't stop saying that it needs Statz. 

[11:04:19] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Statz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        ... 17 more

**Comment by Staartvin** [comment]
Can you check if this issue still occurs on the latest version? Re-open the issue if it still occurs!
