### ISSUE TITLE
Where are you?

### ISSUE THREAD

**Issue by MrKiller01** [Staartvin/Statz#107]
Hi, I can understand when people have a lot to do they abandon things, but If you want to abandon STATZ, please, let us properly know... speculations regarding you being there attending to your plugin, makes people think the weirdest things nowadays.....

Thanks...

**Comment by MrKiller01** [comment]
Why I ask? 

> [14:16:26] [Server thread/ERROR]: Could not pass event InventoryClickEvent to St
atz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2133) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:144) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:118) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java
:908) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile
:103) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:884) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:818) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254)
 ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        ... 17 more
[14:16:27] [Server thread/ERROR]: Could not pass event InventoryClickEvent to St
atz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2133) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:144) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:118) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java
:908) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile
:103) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:884) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:818) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254)
 ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        ... 17 more
[14:18:35] [Server thread/ERROR]: Could not pass event InventoryClickEvent to St
atz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2133) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:144) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:118) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java
:908) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile
:127) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:885) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:818) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254)
 ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        ... 17 more
[14:18:37] [Server thread/ERROR]: Could not pass event InventoryClickEvent to St
atz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2133) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:144) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:118) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java
:908) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile
:103) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:884) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:818) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254)
 ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        ... 17 more
[14:18:39] [Server thread/ERROR]: Could not pass event InventoryClickEvent to St
atz v1.5.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2133) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:144) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:118) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java
:908) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:901) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile
:103) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:884) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:818) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254)
 ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
        ... 17 more
>

>

**Comment by Staartvin** [comment]
I'm not abandoning any of plugins. Currently, I'm working at Solar Team Eindhoven fulltime and will go to Australia for a few months. After I'm back (around December of this year) I'll resume my normal schedule and start working on my plugins again.

**Comment by Staartvin** [comment]
I'm back and have updated the plugin. Make sure to check it out!
