### ISSUE TITLE
Creative item pickup.

### ISSUE THREAD

**Issue by jkapas** [Staartvin/Statz#109]
Every time someone picks an item from creative mode the plugins keep spamming the same Error Code to console.

[18:23:38] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to Statz v1.5.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2289) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:908) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:901) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:818) [spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
	at me.staartvin.statz.gui.GUIManager.onClickInvSlot(GUIManager.java:254) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-6a14ca4-1215188]
	... 17 more

**Comment by Staartvin** [comment]
This issue should be fixed in the latest version of Statz. Could you try to test it with this version?
