### ISSUE TITLE
Votifier - Stacktrace (Seams not compatible with original Votifier.)

### ISSUE THREAD

**Issue by ZachryWilsn** [Staartvin/Statz#11]
Here is the info I gather from adding Statz with Original Votifier.
NuVotifier does not seam to work correctly on my setup and have
had no issues with the Original Votifier to need to change.

`[16:09:28 WARN]: java.lang.NoClassDefFoundError: com/vexsoftware/votifier/NuVotifierBukkit
[16:09:28 WARN]:    at me.staartvin.statz.hooks.handlers.NuVotifierHandler.get(NuVotifierHandler.java:39)
[16:09:28 WARN]:    at me.staartvin.statz.hooks.handlers.NuVotifierHandler.isInstalled(NuVotifierHandler.java:64)
[16:09:28 WARN]:    at me.staartvin.statz.hooks.handlers.NuVotifierHandler.setup(NuVotifierHandler.java:74)
[16:09:28 WARN]:    at me.staartvin.statz.hooks.DependencyManager.loadDependencies(DependencyManager.java:134)
[16:09:28 WARN]:    at me.staartvin.statz.Statz.onEnable(Statz.java:121)
[16:09:28 WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[16:09:28 WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:09:28 WARN]:    at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:216)
[16:09:28 WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:09:28 WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[16:09:28 WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[16:09:28 WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:09:28 WARN]: Caused by: java.lang.ClassNotFoundException: com.vexsoftware.votifier.NuVotifierBukkit
[16:09:28 WARN]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[16:09:28 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[16:09:28 WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:09:28 WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:09:28 WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:09:28 WARN]:    ... 17 more
[16:09:28 WARN]: java.lang.NoClassDefFoundError: com/vexsoftware/votifier/NuVotifierBukkit
[16:09:28 WARN]:    at me.staartvin.statz.hooks.handlers.NuVotifierHandler.get(NuVotifierHandler.java:39)
[16:09:28 WARN]:    at me.staartvin.statz.hooks.handlers.NuVotifierHandler.setup(NuVotifierHandler.java:80)
[16:09:28 WARN]:    at me.staartvin.statz.hooks.DependencyManager.loadDependencies(DependencyManager.java:134)
[16:09:28 WARN]:    at me.staartvin.statz.Statz.onEnable(Statz.java:121)
[16:09:28 WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[16:09:28 WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:09:28 WARN]:    at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:216)
[16:09:28 WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:09:28 WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[16:09:28 WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[16:09:28 WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[16:09:28 WARN]:    at java.lang.Thread.run(Thread.java:745)
[16:09:28 ERROR]: Error occurred while enabling Statz v1.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/vexsoftware/votifier/NuVotifierBukkit

> ```
>   at me.staartvin.statz.hooks.handlers.NuVotifierHandler.setup(NuVotifierHandler.java:80) ~[?:?]
>   at me.staartvin.statz.hooks.DependencyManager.loadDependencies(DependencyManager.java:134) ~[?:?]
>   at me.staartvin.statz.Statz.onEnable(Statz.java:121) ~[?:?]
>   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:216) [MassiveLag.jar:?]
>   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [craftbukkit.jar:git-Spigot-90f61bc-83a9dbd]
>   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`
> ```

**Comment by Staartvin** [comment]
So, to straighten this up. You have NuVotifier installed, but **not Votifier** and Statz 1.3 prints this error?

**Comment by ZachryWilsn** [comment]
No, I Dont use Nu, I use the Original Votifier.
