### ISSUE TITLE
Couldn't execute MySQL statement: [...] Data too long for column 'reason' at row 1

### ISSUE THREAD

**Issue by lerokko** [Staartvin/Statz#146]
I started using Statz with mysql on my server 2 days ago and this pops up in console every other hour.
My server is running **Paper version git-Paper-379 (MC: 1.18.2)** (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
Statz version: 1.7.0 (acc. to /statz) or 1.6.2 (acc. to spigot download page)

```
- [Wed 14:33:11 ERROR Statz] Couldn't execute MySQL statement:
java.sql.BatchUpdateException: Data truncation: Data too long for column 'reason' at row 1
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
    at com.mysql.cj.util.Util.getInstance(Util.java:167)
    at com.mysql.cj.util.Util.getInstance(Util.java:174)
    at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
    at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:897)
    at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800)
    at Statz-1.7.0.jar//com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
    at Statz-1.7.0.jar//com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
    at Statz-1.7.0.jar//me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:949)
    at Statz-1.7.0.jar//me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:81)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lerokko** [comment]
Just bumping this. It still show up when player join occasionally. On paper 307 and Statz 1.7.0. Dunno how severe this bug is.
