### ISSUE TITLE
Statz plugin console error

### ISSUE THREAD

**Issue by Gasha666** [Staartvin/Statz#32]
Please help me i'm using Statz and Autorank i got this spamming error from statz and i don't know how to fix it.. i'm using latest version of autorank and statz.. please answer me soon as possible i'm running big server and i don't know what to do now

  Could not pass event EntityDeathEvent to Statz v1.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378)
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874)
	at net.minecraft.server.v1_8_R3.EntitySkeleton.die(EntitySkeleton.java:142)
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812)
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42)
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001)
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063)
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355)
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: STRAY
	at me.staartvin.statz.util.StatzUtil.getMobType(StatzUtil.java:683)
	at me.staartvin.statz.listeners.KillsMobsListener.onDie(KillsMobsListener.java:50)
	at sun.reflect.GeneratedMethodAccessor611.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	... 22 more

**Comment by Staartvin** [comment]
Solved through Spigot PM's. Recommended to use lower version of Statz (made for Minecraft 1.8)
