### ISSUE TITLE
error with paper spigot 1.8.8 server

### ISSUE THREAD

**Issue by edvinsdainis1001** [Staartvin/Statz#40]
[20:51:24] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Statz v1.4.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:884) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
	at me.staartvin.statz.listeners.KillsMobsListener.onDie(KillsMobsListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
	... 22 more

This is happening on all my 1.8.8 servers using paper spigot

**Comment by Staartvin** [comment]
The latest version of Statz only supports MC 1.9 and up. Either upgrade your MC version or downgrade Statz.
