### ISSUE TITLE
[broken] Tried to migrate from Stats3, Failed, Errors and Server crash.

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Statz#43]
Hello!

I tried to migrate from stats3 to Statz today, but it spammed errors then crashed the server.
Heres a log of what happens when I run /statz migration from console
http://pastebin.com/G2zsKWyQ

**Comment by Staartvin** [comment]
Hmm, what version of Statz are you running?

**Comment by FrozenBeard** [comment]
@Staartvin 1.4.2
Please fix this, I cant stand Stats3 any longer, I have so many issues with it, Seriously I have it literally deleting random data from the database...

**Comment by Staartvin** [comment]
It seems Statz cannot connect to your database. Could you provide your startup log as well?

**Comment by FrozenBeard** [comment]
'''
[12:44:27 INFO]: [Statz] Enabling Statz v1.4.2
[12:44:27 INFO]: [Statz debug] Using MySQL database!
[12:44:27 INFO]: [Statz debug] ---------------[Statz Dependencies]---------------
[12:44:27 INFO]: [Statz debug] Searching dependencies...
[12:44:27 INFO]: [Statz debug] OnTime has not been found!
[12:44:27 INFO]: [Statz debug] afkTerminator has not been found!
[12:44:27 INFO]: [Statz debug] AcidIsland has not been found!
[12:44:27 INFO]: [Statz debug] RoyalCommands has not been found!
[12:44:27 INFO]: [Statz debug] NuVotifier was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] GriefPrevention was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] Votifier has not been found!
[12:44:27 INFO]: [Statz debug] mcMMO has not been found!
[12:44:27 INFO]: [Statz debug] UltimateCore has not been found!
[12:44:27 INFO]: [Statz debug] Vault was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] Factions has not been found!
[12:44:27 INFO]: [Statz debug] Statistics has not been found!
[12:44:27 INFO]: [Statz debug] RPGme has not been found!
[12:44:27 INFO]: [Statz debug] Stats was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] Essentials was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] WorldGuard was found and Statz now tracks its data!
[12:44:27 INFO]: [Statz debug] Jobs has not been found!
[12:44:27 INFO]: [Statz debug] ASkyBlock has not been found!
[12:44:27 INFO]: [Statz debug] ---------------[Statz Dependencies]---------------
[12:44:27 INFO]: [Statz debug] Loaded libraries and dependencies
[12:44:27 INFO]: [Statz debug] Statz won't track stats of any player!
[12:44:27 INFO]: [Statz] Language file loaded (lang.yml)
[12:44:27 INFO]: [Statz] Stats disabled file loaded (disabled-stats.yml)
[12:44:27 INFO]: [Statz] Statz v1.4.2 has been enabled!
'''

**Comment by Staartvin** [comment]
Could you show your whole startup log, since I need a little bit more info.

**Comment by FrozenBeard** [comment]
I't was failing to connect I didn't wrap my password in '', I fixed this, made sure it created the tables in the MySQL to make sure 100% it was connecting, and ran migrate again, it crashed the server instantly.

```
>statz migrate
[15:27:11 INFO]: Start migrating data from Stats 3 to Statz!
[15:27:11 INFO]: This may take a while.
[15:27:15 WARN]: Failed to load player data for 57f49c77-157f-432d-9213-b7f6aa06b4a7
[15:27:15 WARN]: Failed to load player data for a5c149e2-71bf-4b30-8c38-740fa8ea786e
[15:27:20 WARN]: [Statz] Plugin Statz v1.4.2 generated an exception while executing task 12649
java.lang.NullPointerException
        at me.staartvin.statz.importer.ImportManager.importFromStats3(ImportManager.java:139) ~[?:?]
        at me.staartvin.statz.commands.MigrateCommand$1.run(MigrateCommand.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.10.2.jar:git-Paper-916]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.10.2.jar:git-Paper-916]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[15:27:21 WARN]: Failed to load player data for 57f49c77-157f-432d-9213-b7f6aa06b4a7
[15:27:21 ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_121]
        at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[?:1.8.0_121]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:374) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[15:27:23 ERROR]: This crash report has been saved to: /home/tom/piratecraft/survival/./crash-reports/crash-2017-03-21_15.27.23-server.txt
[15:27:23 INFO]: Stopping server
```

**Comment by FrozenBeard** [comment]
Doubled the server to use 8GB ram, still crashed.
```
>statz migrate
[15:31:24 INFO]: Start migrating data from Stats 3 to Statz!
[15:31:24 INFO]: This may take a while.
[15:31:27 WARN]: Failed to load player data for 57f49c77-157f-432d-9213-b7f6aa06b4a7
[15:31:28 WARN]: Failed to load player data for a5c149e2-71bf-4b30-8c38-740fa8ea786e
[15:31:33 WARN]: [Statz] Plugin Statz v1.4.2 generated an exception while executing task 13120
java.lang.NullPointerException
        at me.staartvin.statz.util.StatzUtil.makeQuery(StatzUtil.java:61) ~[?:?]
        at me.staartvin.statz.importer.ImportManager.importFromStats3(ImportManager.java:215) ~[?:?]
        at me.staartvin.statz.commands.MigrateCommand$1.run(MigrateCommand.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.10.2.jar:git-Paper-916]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.10.2.jar:git-Paper-916]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[15:31:34 WARN]: Failed to load player data for 57f49c77-157f-432d-9213-b7f6aa06b4a7
[15:31:35 ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_121]
        at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[?:1.8.0_121]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:374) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) ~[patched_1.10.2.jar:git-Paper-916]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[15:31:37 ERROR]: This crash report has been saved to: /home/tom/piratecraft/survival/./crash-reports/crash-2017-03-21_15.31.36-server.txt
[15:31:37 INFO]: Stopping server
```

**Comment by FrozenBeard** [comment]
Bump. This is still broken.

**Comment by FrozenBeard** [comment]
Bump, I need an alternative to Stats3.

**Comment by Staartvin** [comment]
Hey, so do you have any logs of trying to convert from Stats 3 to Statz? (more than are shown here) Or does it just crash?

**Comment by FrozenBeard** [comment]
It crashes.

**Comment by Staartvin** [comment]
Could you provide the crash report? (in the crash-reports folder)

**Comment by Staartvin** [comment]
Hey, thanks so me reminding me again. I was looking at this but I need your database of Stats 3 so I can test the migrate issue. Could you provide the dump? I think you've already done before, but I can't seem to find it.

**Comment by FrozenBeard** [comment]
@Staartvin I have haha! I can do it again, no worries. its a bit big, I don't want it public so can I sent the link over Skype or discord again?

**Comment by Staartvin** [comment]
Discord is fine, do you have me on Discord? (@Staartvin).

**Comment by Staartvin** [comment]
Just curious, how many users do you have in your Stats database?

**Comment by FrozenBeard** [comment]
Since were coming up to 2019 and I need AutoRank multi ranks working, I need to convert, you dont support Stats version 3.1.1-RC, so Attempting to migrate to Statz again and cant get it to even start properly.
Talking to your mod on Discord I was told to use Statz 1.5.1 on Paper 1.12.2 with PluginLibrary 1.1. I run ./statz migrate stats3 and it gives me this:
https://pastebin.com/CGvxbHU5

I have tried every over version of Statz and PluginLibrray higher than the versions I have installed now.
I have 111,000+ Users in my Stats3 database.
