### ISSUE TITLE
Exception while executing task 17

### ISSUE THREAD

**Issue by jeffm13** [Staartvin/Statz#53]
New server (and operator), so maybe I'm doing everything wrong.  Installed latest Statz on a Spigot 1.12.1 server on Linux. 

```

[14:22:48] [Craft Scheduler Thread - 2/WARN]: [Stats] Plugin Stats v3.1.1-RC generated an exception while executing task 17
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_141]
        at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_141]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:239) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.Gson.toJson(Gson.java:648) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.Gson.toJson(Gson.java:603) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at com.google.gson.Gson.toJson(Gson.java:583) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at nl.lolmewn.stats.storage.FlatfileStorageEngine.save(FlatfileStorageEngine.java:88) ~[?:?]
        at nl.lolmewn.stats.user.StatsUserManager.saveUser(StatsUserManager.java:36) ~[?:?]
        at nl.lolmewn.stats.bukkit.BukkitMain.lambda$null$2(BukkitMain.java:281) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566) ~[?:1.8.0_141]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_141]
        at nl.lolmewn.stats.bukkit.BukkitMain.lambda$scheduleDataSaver$3(BukkitMain.java:279) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

```
This is happening every 10 seconds....

My config.yml looks like this: 

```
track stats: true
show database save message: true
mysql:
  enabled: false
  hostname: localhost:3306
  username: root
  password: ''
  database: Statz
periodic save time: 10
disabled statistics:
- DISABLED_STAT_NAME_HERE
- OTHER_DISABLED_STAT_NAME
ignore creative: false
enable debug output: true
latest patch mysql version: 0
latest patch sqlite version: 1
use custom statz list: false
custom statz list:
- JOINS
- FOOD_EATEN
- KILLS_PLAYERS
```
Changing the ```periodic save time```, ```enable debug output```, and ```show database save message``` settings does not work--the values I set are overwritten everytime the server starts.

I currently do not have either mysql or sqlite set up...

**Comment by Staartvin** [comment]
I see you provided the config of Statz, but that error log is something of Stat**s** (with an s). It's made by [Lolmewn](https://dev.bukkit.org/projects/lolmewnstats). It might be more helpful to contact him. Note that it is outdated (I believe). 

If you have any other errors, I'm glad to help!

**Comment by jeffm13** [comment]
Oops...  thanks. My fault.  However, the second part of the problem (config.yml getting overwritten) is definitely a problem--I'm getting debug output every 10 seconds in the log.  Can you check on that?

**Comment by Staartvin** [comment]
Try stopping your server, changing the config file, save it and then restart your server. That should do the thing! You cannot change the file while the server is on.

**Comment by Staartvin** [comment]
It should be fixed in the latest dev build (16)
