### ISSUE TITLE
CustomUtils and Gravestone Plugin

### ISSUE THREAD

**Issue by MCTyler** [Staartvin/Statz#66]
Hi, I added the two plugins above and now I'm receiving this error when a player dies. Any easy fix?

> [22:10:11 ERROR]: [Statz] Couldn't execute MySQL statement:
java.sql.BatchUpdateException: Data truncation: Out of range value for column 'value' at row 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:970) [Statz-1.4.5.jar:?]
	at me.staartvin.statz.datamanager.DataPoolManager.forceSendPool(DataPoolManager.java:276) [Statz-1.4.5.jar:?]
	at me.staartvin.statz.datamanager.DataPoolManager$1.run(DataPoolManager.java:233) [Statz-1.4.5.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'value' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	... 9 more
>

**Comment by Staartvin** [comment]
Are you still experiencing this issue with the latest version of Statz?

**Comment by MCTyler** [comment]
I quit using it....Sry.

**Comment by Dream-cake** [comment]
i am

**Comment by Dream-cake** [comment]
its this plugin https://www.spigotmc.org/resources/deathchest.75186/
