### ISSUE TITLE
SQLiteConnector: BatchUpdateException

### ISSUE THREAD

**Issue by Deku** [Staartvin/Statz#7]
Using last version available on Spigot.

Stacktrace:

[12:11:45 ERROR]: [Statz] Couldn't execute SQLite statement:
java.sql.BatchUpdateException: batch entry 1: [SQLITE_ERROR] SQL error or missing database (no such column: Infinity)
        at org.sqlite.Stmt.executeBatch(Stmt.java:226) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
        at me.staartvin.statz.database.SQLiteConnector.setBatchObjects(SQLiteConnector.java:622) [Statz-1.2.1.jar:?]
        at me.staartvin.statz.datamanager.DataPoolManager.forceSendPool(DataPoolManager.java:297) [Statz-1.2.1.jar:?]
        at me.staartvin.statz.datamanager.DataPoolManager$1.run(DataPoolManager.java:269) [Statz-1.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]

**Comment by Staartvin** [comment]
You should delete the column that has 'infinity' in it. You can use a program called SQLiteDatabaseBrowser

**Comment by Deku** [comment]
You are not getting it. The plugin is trying to execute a statement which includes a reference to a column named "Infinity", that doesn't exists. Will debug in my local env and report later (maybe with a PR).

Greetings

**Comment by Staartvin** [comment]
I've had this problem before. You'll find an entry (or multiple) in your database that has a 'infinity value'  for some column. If you remove those entries, Statz will continue to operate again.
