### ISSUE TITLE
Do you have any post to WIKI ?

### ISSUE THREAD

**Issue by jariojose** [Staartvin/Statz#72]
I am a starter develop. So, I am trying to put a scoreboard in my server. But, I am having:

`org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.staartvin.statz.api.API.getTotalOf(API.java:42) ~[?:?]
	at com.craftandobr.TesteBoard.PlayerJoin(TesteBoard.java:70) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	... 14 more`

My code:

`    static Plugin plugin;
    Plugin statz = Bukkit.getServer().getPluginManager().getPlugin("Statz");

    @Override
    public void onEnable() {
        plugin = this;
        Bukkit.getServer().getPluginManager().registerEvents(this, this);

    }

    ScoreboardManager manager;
    Scoreboard board;
    Objective objective;

    @EventHandler
    public void PlayerJoin(PlayerJoinEvent e) {

        manager = Bukkit.getScoreboardManager();
        board = manager.getNewScoreboard();
        objective = board.registerNewObjective("test", "dummy");

        final Player p = e.getPlayer();

        API statzApi = null;
        
        if (statz != null && statz.isEnabled()) {
            statzApi = new API((Statz) statz);

        }

        System.out.println("StatsAPI: " + statzApi.toString());
        
        Double deaths = statzApi.getTotalOf(PlayerStat.DEATHS, p.getUniqueId(), "spawn");

        Bukkit.getServer().getScheduler().scheduleSyncRepeatingTask(ScoreBoardPlayer.plugin, new Runnable() {
            @Override
            public void run() {

                ScoreboardManager manager = Bukkit.getScoreboardManager();
                final Scoreboard board = manager.getNewScoreboard();
                final Objective objective = board.registerNewObjective("test", "dummy");

                objective.setDisplaySlot(DisplaySlot.SIDEBAR);
                objective.setDisplayName(ChatColor.RED + "EpsilonMC");

                Score score = objective.getScore(ChatColor.AQUA + "Player name:");
                score.setScore(10);

                Score score1 = objective.getScore(ChatColor.GRAY + p.getName());
                score1.setScore(9);

                Score score2 = objective.getScore(ChatColor.AQUA + "Health:");
                score2.setScore(8);

                long health = Math.round(deaths);

                Score score3 = objective.getScore(ChatColor.GRAY + String.valueOf(health));
                score3.setScore(7);

                p.setScoreboard(board);

            }
        }, 0, 20 * 10);

    }`

**Comment by jariojose** [comment]
I was bad coding. The

>  Plugin statz = Bukkit.getServer().getPluginManager().getPlugin("Statz");

must inserted into onEnable methods :+1: 

Thank you!
