### ISSUE TITLE
Skip database sync as there is still one running. ConcurrentModificationException: Null

### ISSUE THREAD

**Issue by jariojose** [Staartvin/Statz#76]
Hello, @Staartvin 

Statz skips database sync as there is still one running.

`[10:20:55] [Craft Scheduler Thread - 15/WARN]: [Statz] Plugin Statz v1.5.1 generated an exception while executing task 76
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_171]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_171]
	at me.staartvin.statz.update.UpdatePoolManager.getUpdateQueriesCopy(UpdatePoolManager.java:87) ~[?:?]
	at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-2086bb0-21d5f75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[10:21:05] [Craft Scheduler Thread - 23/INFO]: [Statz debug] Skip database sync as there is still one running.[m`

**Comment by cheeseries** [comment]
is there a solution for this yet?

**Comment by Staartvin** [comment]
Hmm, I'm still working on this issue, but it should be resolved soon (hopefully). When do you get this error? At random? Or only during logging in/out of a player? Is it periodic?

**Comment by cheeseries** [comment]
It starts just after startup when a player first logs in. Weve actually moved onto a differnt plugin so thats all the information i have now.

**Comment by Staartvin** [comment]
Try this version: http://178.62.255.148:8080/job/Statz/49/

**Comment by Staartvin** [comment]
See [this one](https://ci.staartvin.com/job/Statz/52/) as well, it ought to fix it.
