### ISSUE TITLE
Executing task 56

### ISSUE THREAD

**Issue by muddup** [Staartvin/Statz#77]
Here is what appears in server log:

[21:24:34 WARN]: [Statz] Plugin Statz v1.5.1 generated an exception while execut
ing task 56
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.
8.0_171]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_171]
        at me.staartvin.statz.update.UpdatePoolManager.getUpdateQueriesCopy(Upda
tePoolManager.java:87) ~[?:?]
        at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.ja
va:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:76) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_171]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

Doesn't realy happen all the time, and doesn't seem to bother the server that I or others have noticed.
So just curious as what may cause this.

Great plugin though, thanks for all your hard work on this.

Muddup

**Comment by Staartvin** [comment]
I've got this issue already on my bugtracker. Thanks for notifying me again, I'm working on fixing it!
