### ISSUE TITLE
Having problem connecting with PlaceholderAPI

### ISSUE THREAD

**Issue by wanhe886** [Staartvin/Statz#79]
I am using a scoreboard to display the statz, and I got this.

--------------------------
[18:27:07] [Server thread/WARN]: [ScoreboardPlus] Task #55 for ScoreboardPlus v10 generated an exception
java.lang.NoClassDefFoundError: me/staartvin/statz/datamanager/PlayerStat
	at me.glaremasters.statzexpansion.StatzExpansion.onPlaceholderRequest(StatzExpansion.java:96) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:212) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:188) ~[?:?]
	at me.kaaseigenaar.scoreboard.ScoreboardBuilder.buildScoreboard(ScoreboardBuilder.java:107) ~[?:?]
	at me.kaaseigenaar.scoreboard.events.worlds.run(worlds.java:60) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by Staartvin** [comment]
It seems that this extension uses an outdated version of Statz. The developer (not me, I did not make this extension) should update the dependency.
