### ISSUE TITLE
1.5.1 - Database not getting updated after a while

### ISSUE THREAD

**Issue by Kahval** [Staartvin/Statz#82]
This problem only happens in version 1.5 and above. I downgraded to 1.4.5 to avoid this problem. After I restart the server Plugin does update the database for a while. About 4-6 hours later this exception pops up:
`java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_171]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_171]
	at me.staartvin.statz.update.UpdatePoolManager.getUpdateQueriesCopy(UpdatePoolManager.java:87) ~[?:?]
	at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-"4886fbd3"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-"4886fbd3"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-"4886fbd3"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

After that, database update task stops working but the other task, which loads data from database, still continues to work. This causes in-game real time values to be overwritten with old values from db and players complain their stats are rollback constantly.

**Comment by Staartvin** [comment]
Could you try run this version: http://178.62.255.148:8080/job/Statz/48/ and report back to me with the results?

**Comment by Kahval** [comment]
Okey I will give you a feedback

**Comment by Kahval** [comment]
That version seem to be working fine. No errors and database is getting updated regularly. Thank you.

**Comment by Staartvin** [comment]
Very good to hear. I'll close this issue then.
