### ISSUE TITLE
Statz Data truncation: Data too long for column 'arguments' at row 1

### ISSUE THREAD

**Issue by iSkyify** [Staartvin/Statz#89]
Here is an error from Statz v 1.5.2  (also running autorank 4.2.5 and Paper Spigot 1.12.2 1474) https://hastebin.com/mepotulemu.sql
`[07:05:20] [Craft Scheduler Thread - 49/ERROR]: [Statz] Couldn't execute MySQL statement:
java.sql.BatchUpdateException: Data truncation: Data too long for column 'arguments' at row 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at me.staartvin.statz.database.MySQLConnector.setBatchObjects(MySQLConnector.java:967) [Statz-1.5.2.jar:?]
	at me.staartvin.statz.tasks.UpdateDatabaseTask.run(UpdateDatabaseTask.java:81) [Statz-1.5.2.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) [PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'arguments' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[PaperSpigot-%5b1.12.2%5d-%5bBuild1474%5d.jar:git-Paper-1474]
	... 9 more`

**Comment by Magnum97** [comment]
I am also getting this error with a fresh server and fresh SQL database.
Server: Paper 1.15.2 build 208
Statz: v 1.5.5
Are previous versions 1.15 friendly? Considering a rollback to get it going. I use it for autorank dependency.

**Comment by Staartvin** [comment]
No, not all versions are 1.15 compatible, especially not Statz (since it uses blocks that didn't exist yet).

**Comment by Staartvin** [comment]
Hmm, I think I know what the issue is here. Let me try to fix it and give you a dev build.

**Comment by Staartvin** [comment]
Could you try to use this version and see if the errors still occur: http://staartvin.com:8080/job/Statz/17/

**Comment by Magnum97** [comment]
Fabulous thank you so much. I will load this tonight and update you.

**Comment by Magnum97** [comment]
@Staartvin Update on this issue for you:
After 24 hours I do not see that error in the logs anywhere. However we do have a different error. https://hatebin.com/oeatlovlst
Not always the same command but it says the same about duplicate keys.

**Comment by Staartvin** [comment]
When do you get this and how frequent is it?

**Comment by Magnum97** [comment]
From the last full day's log file:
<pre>
[01:21:52] [Craft Scheduler Thread - 7027/ERROR]: [Statz] Couldn't execute MySQL statement:
[13:12:21] [Craft Scheduler Thread - 13871/ERROR]: [Statz] Couldn't execute MySQL statement:
[13:50:12] [Craft Scheduler Thread - 14396/ERROR]: [Statz] Couldn't execute MySQL statement:
[18:25:03] [Craft Scheduler Thread - 2990/ERROR]: [Statz] Couldn't execute MySQL statement:
[20:11:02] [Craft Scheduler Thread - 4032/ERROR]: [Statz] Couldn't execute MySQL statement:
</pre>
So.. not that regularly but not in any pattern I recognize.
